version: '3.3'

services:
  merity-backend-db:
    container_name: merity-backend-db
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend

  merity-backend:
    container_name: merity-backend
    build:
      context: ../rewards-backend/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - merity-backend-db
    working_dir:
      "/usr/src/app"
    volumes:
      - '../rewards-backend:/usr/src/app'
      - "/usr/src/app/node_modules"
    environment:
      - DB_HOST=merity-backend-db
      - DB_NAME=backend
      - DB_USER=backend
      - DB_PASSWORD=backend
    command: ['npm', 'run', 'dev:smart:with-migrations']

  merity-frontend:
    container_name: merity-frontend
    build:
      context: ../rewards-frontend
      dockerfile: Dockerfile
    volumes:
      - '../rewards-frontend:/usr/src/app'
      - "/usr/src/app/node_modules"
    environment:
      - WEB_SERVER_PORT=3000
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev:smart']
